extends:
  - airbnb

parser: babel-eslint

env:
  browser: true
  node: true

settings:
  import/resolver:
    - node


rules:
  import/extensions: 0
  react/prop-types: 0
  max-len: 0
  no-console: 0